### ISSUE TITLE
[Windows] bxt-rs from GitHub Actions cannot be injected

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/bxt-rs#27]
![0](https://user-images.githubusercontent.com/58108407/141607138-c32f353a-eebd-49f7-b79a-b75305f582c5.PNG)

**Comment by SmileyAG** [comment]
@hobokenn Please, check out it when will you have free time.

**Comment by YaLTeR** [comment]
According to @SmileyAG, apparently only GitHub Actions builds are affected, while building manually works fine.

I'm really not sure what this could be caused by. As far as I can tell, it's not the dependency cache because without `Cargo.lock` cargo should always use the latest dependency versions (so same as manual `cargo update` + build). Otherwise there's nothing special in the CI pipeline.

**Comment by YaLTeR** [comment]
Looks like it's https://github.com/rust-lang/rust/issues/88576, which is a bug introduced in Rust 1.56.0. Rust 1.55.0 and (as of today) nightly builds work fine. I'll see if I can come up with a workaround until it's backported.

**Comment by YaLTeR** [comment]
Added workaround in https://github.com/YaLTeR/bxt-rs/commit/8f8e78b227afb38872b442599ca9a447163f1ba6.
